name: Gatsby Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PREFIX_PATHS: true
    steps:
      - uses: actions/checkout@v3
      - uses: enriikke/gatsby-gh-pages-action@v2    
        with:
          access-token: x-access-token:${{ secrets.GITHUB_TOKEN }}
          git-config-name: GithubActionsBot
          git-config-email: deploybot@scvconsultants.com
          deploy-branch: gh-pages